Repository mandatory-coding-club/algorithm-lecture-study, pull requests merged in 2025-09, with the labels that each got.

#3 [5] 문제풀이/채원
  5_problem-solving-patterns/1_chaewon.js
  5_problem-solving-patterns/2_chaewon.js
  5_problem-solving-patterns/3-1_chaewon.js
  5_problem-solving-patterns/3-2_chaewon.js
  5_problem-solving-patterns/4_chaewon.js
Labels: summary

#2 [5] 문제풀이/yunjeong
  5_problem-solving-patterns/1_yunjeong.js
  5_problem-solving-patterns/2_yunjeong.js
  5_problem-solving-patterns/3-1_yunjeong.js
  5_problem-solving-patterns/3-2_yunjeong.js
  5_problem-solving-patterns/4_yunjeong.js
Labels: summary

#1 [5강] 문제 해결 패턴 학습 정리 & 과제
  5_problem-solving-patterns/1_chaeyoung.js
  5_problem-solving-patterns/2_chaeyoung.js
  5_problem-solving-patterns/3_chaeyoung.js
  5_problem-solving-patterns/4_chaeyoung.js
  5_problem-solving-patterns/chaeyoung.md
Labels: lecture-notes, summary

#9 [8] 문제풀이/yunjeong
  08_recursion-problem-set/1_yunjeong.js
  08_recursion-problem-set/2_yunjeong.js
  08_recursion-problem-set/3_yunjeong.js
  08_recursion-problem-set/4_yunjeong.js
  08_recursion-problem-set/5_yunjeong.js
Labels: problem-solving

#16 [10] 문제풀이 / yunjeong
  10_search-algorithms/1_yunjeong.js
  10_search-algorithms/2_yunjeong.js
  10_search-algorithms/3_yunjeong.js
Labels: problem-solving

#15 [10]문제풀이/chaeyoung
  10_search-algorithms/.gitkeep
  10_search-algorithms/1_chaeyoung.js
  10_search-algorithms/2_chaeyoung.js
  10_search-algorithms/3_chaeyoung.js
Labels: problem-solving
